#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         3
bspc config window_gap           2

bspc config focused_border_color "#880000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xwallpaper --center ~/pix/wallpapers/feld.png
picom &
~/session-startup.sh
